### ISSUE TITLE
allowOutsideClick option

### ISSUE THREAD

**Issue by nuryagdym** [rocketlaunchr/electron-alert#8]
Hi,
I am trying create undismissable alert, users will not be able to click outside of the alert box, on full screen app. sweet alert do this by `allowOutsideClick`  to false. I tried with this library, it did not work.

**Comment by pjebs** [comment]
How this package works is it creates a BrowserWindow (non-fullsize) and then loads a website with sweetalert2 inside.
Because the browserwindow is not fullsize, I can't prevent clicks outside.

To achieve your aim, you need to create your own full-size BrowserWindow and load a website and **use** sweetalert2 from the renderer process.

You can't use the library for your purposes.
